### PR TITLE
Implement example logon and password change usage scenarios.

### PR DESCRIPTION
**Pull request by jameswestgate**
Hi @SteveSyfuhs 

Attached is code to demonstrate basic implementation around logon, unlock and password change usage scenarios. It includes credential serialization for the MSV1_0 authentication package.

It also solves some issues around associating user sids with credentials correctly, and a problem where serialization is immediately requested on selection of the credential.

This has been tested on my non-domain joined machine. To anyone evaluating this code, it is probably to use a VM to avoid having to reboot in safe mode should the provider fail badly :)

### CODE REVIEW

**Comment by SteveSyfuhs** [comment]
Wow, very nice! My very quick first pass of this looks good. I haven't tried it out yet. Will try and take a look a little later today.

Where'd the icon come from? Did you create it yourself?

**Comment by jameswestgate** [comment]
The icon is actually from another project, I believe originally Free Icons. I've just checked their licence and it's a bit unclear, so I've replaced it with a quick and dirty photoshop version I just made.

**Comment by SteveSyfuhs** [comment]
Looks good to me!

**Comment by jameswestgate** [comment]
Whoop! Do you think there’s any mileage in using SecureString instead of string, since we are dealing with credentials etc?

**Comment by SteveSyfuhs** [comment]
SecureString isn't really ever a good idea. It doesn't actually make it secure because the creds are already in managed memory. This is a relatively low risk. The process is running as system and doesn't get paged.

**Comment by SteveSyfuhs** [comment]
Or I guess the better answer is that a there's some major work required to make it so the creds are never stored in managed memory. It's possible to do, but SecureString isn't the answer for that.

**Comment by jameswestgate** [comment]
Ok thanks, that's super useful to know. I was thinking of modifying the .idl to pass a pointer and marshalling the string values manually, but it seems like its more an interesting technical exercise than anything that adds much value.

**Pull request merged**
